import { app, BrowserWindow, ipcMain } from 'electron';
import initLogger from './logger';
import initPodman from './podman-desktop/simple-container-manage';
import initCmd from './cmd';
import initConfigs from './configs';
import initObsidianPlugin, { updateTemplate } from './obsidian-plugin';
import initWorkspace from './workspace';
import initContainerLogs from './podman-desktop/container-logs';
import initLMStudio from './lm-studio';
import initExampleMain from './example-main';
import initTerminalLog from './terminal-log';
import initPdfConvert from './pdf-convert';
import initTrainingService from './training-service';
import initLogService from './backup';
import initExternalUrl from './external-url';
import initWebtorrent from './webtorrent';
import initDlc from './dlc';
import path from 'node:path';
import { appPath, autoAdaptEncodingForWindows } from './exec';
import { logDeviceInfo } from './logger/log-device-info';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

initLogger();

// 防止应用多开 - 单实例锁
const gotTheLock = app.requestSingleInstanceLock();

if (!gotTheLock) {
  // 如果已经有实例在运行，则退出当前进程
  console.log('应用已在运行中，退出当前实例');
  app.quit();
} else {
  // 这是第一个实例，继续初始化
  app.on('second-instance', (event, commandLine, workingDirectory) => {
    // 当用户尝试运行第二个实例时，聚焦到已存在的窗口
    const windows = BrowserWindow.getAllWindows();
    if (windows.length > 0) {
      const mainWindow = windows[0];
      if (mainWindow.isMinimized()) {
        mainWindow.restore();
      }
      mainWindow.focus();
    }
  });
}

// 在适当的位置初始化日志服务
initLogService(ipcMain);

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

async function firstLog() {
  console.log('源码版本', __COMMIT_HASH__);
  console.log('版本号', __NPM_PACKAGE_VERSION__);
  await autoAdaptEncodingForWindows();
  await logDeviceInfo();
}

firstLog();

app.commandLine.appendSwitch('--enable-logging', 'file');
app.commandLine.appendSwitch('--log-file', path.join(appPath, 'chrome.log'));

initCmd(ipcMain);
initConfigs(ipcMain);
initObsidianPlugin(ipcMain);
initWorkspace(ipcMain);
initContainerLogs(ipcMain);
initLMStudio(ipcMain);
initExampleMain(ipcMain);
initPdfConvert(ipcMain);
initTrainingService(ipcMain);
initExternalUrl(ipcMain);
initWebtorrent(ipcMain);
updateTemplate();

// 初始化 DLC 下载模块
initDlc(ipcMain);

const createWindow = async () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 720,
    width: 1280,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    show: false,
    autoHideMenuBar: true,
  });

  // 最大化窗口
  mainWindow.maximize();

  // 显示窗口
  mainWindow.show();

  // 需要等待连接podman
  await initPodman(ipcMain);

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  initTerminalLog(mainWindow);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
